# Generated by Django 4.1.8 on 2023-04-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launcher', '0003_contactcompliant_democontactmessage_loginvalidation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='democontactmessage',
            name='subject',
            field=models.CharField(default='', max_length=100),
        ),
    ]
