# Generated by Django 4.1.8 on 2023-04-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launcher', '0004_alter_contactmessage_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginvalidation',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='signupdata',
            name='mail_id',
            field=models.CharField(max_length=100),
        ),
    ]
